config/routes.rb
ImpastoPrelaunch::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :prelaunch_subscribers

  root :to => "prelaunch_subscribers#new"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/prelaunch_subscriber.rb
class PrelaunchSubscriber < ActiveRecord::Base
  attr_accessible :artist, :birthdate, :email, :location, :name, :phone, :portfolio

  validates_presence_of :email, :message => 'Please enter your email address first.'
  validates_uniqueness_of :email, :message => 'That email is already on the list.'
  validates_format_of :email,
    :with => /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/i,
    :message => 'That email address doesn\'t look right.'

  after_save :add_to_campaign_monitor, :if => :campaign_monitor_configured?

  private

  def add_to_campaign_monitor

    if artist
      list_id = PRELAUNCH_CONFIG[:campaign_monitor_artist_list_id]
    else
      list_id = PRELAUNCH_CONFIG[:campaign_monitor_user_list_id]
    end

    custom_fields = [
      { :Key => 'Phone', :Value => phone },
      { :Key => 'Portfolio', :Value => portfolio },
      { :Key => 'Birthdate', :Value => birthdate },
      { :Key => 'Location', :Value => location },
    ]

    CreateSend::Subscriber.add(list_id, email, name, custom_fields, true)
  end

  def campaign_monitor_configured?
    PRELAUNCH_CONFIG[:campaign_monitor_api_key].present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/prelaunch_subscribers_controller.rb
class PrelaunchSubscribersController < ApplicationController

    caches_page :new
    # GET /prelaunch_subscribers
    # GET /prelaunch_subscribers.json
    # def index
    #   @prelaunch_subscribers = PrelaunchSubscriber.all

    #   respond_to do |format|
    #     format.html # index.html.erb
    #     format.json { render :json => @prelaunch_subscribers }
    #   end
    # end

    # # GET /prelaunch_subscribers/1
    # # GET /prelaunch_subscribers/1.json
    # def show
    #   @prelaunch_subscriber = PrelaunchSubscriber.find(params[:id])

    #   respond_to do |format|
    #     format.html # show.html.erb
    #     format.json { render :json => @prelaunch_subscriber }
    #   end
    # end

    # # GET /prelaunch_subscribers/new
    # # GET /prelaunch_subscribers/new.json
    def new
        @prelaunch_subscriber = PrelaunchSubscriber.new

        respond_to do |format|
            format.html # new.html.erb
        end
    end

    # # GET /prelaunch_subscribers/1/edit
    # def edit
    #   @prelaunch_subscriber = PrelaunchSubscriber.find(params[:id])
    # end

    # # POST /prelaunch_subscribers
    # # POST /prelaunch_subscribers.json
    def create
        @prelaunch_subscriber = PrelaunchSubscriber.new(params[:prelaunch_subscriber])

        logger.debug "#{params[:prelaunch_subscriber]}"

        respond_to do |format|
            if @prelaunch_subscriber.save
                format.html { redirect_to root_url }
                format.json { render :json => { :success => true } }
            else
                format.html { render :action => "new" }
                format.json { render :json => { :success => false, :errors => @prelaunch_subscriber.errors } }
            end
        end
        
    end

    # # PUT /prelaunch_subscribers/1
    # # PUT /prelaunch_subscribers/1.json
    # def update
    #   @prelaunch_subscriber = PrelaunchSubscriber.find(params[:id])

        # respond_to do |format|
        #   if @prelaunch_subscriber.update_attributes(params[:prelaunch_subscriber])
        #     format.html { redirect_to @prelaunch_subscriber, :notice => 'Prelaunch subscriber was successfully updated.' }
        #     format.json { head :no_content }
        #   else
        #     format.html { render :action => "edit" }
        #     format.json { render :json => @prelaunch_subscriber.errors, :status => :unprocessable_entity }
        #   end
        # end
    # end

    # # DELETE /prelaunch_subscribers/1
    # # DELETE /prelaunch_subscribers/1.json
    # def destroy
    #   @prelaunch_subscriber = PrelaunchSubscriber.find(params[:id])
    #   @prelaunch_subscriber.destroy

    #   respond_to do |format|
    #     format.html { redirect_to prelaunch_subscribers_url }
    #     format.json { head :no_content }
    #   end
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prelaunch_subscribers_helper.rb
module PrelaunchSubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Impasto</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    "reset", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "prelaunch", :media => "all" %>

  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js "></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
  <%= javascript_include_tag "prelaunch" %>
  <script type="text/javascript">
    WebFontConfig = {
      typekit: { id:'kab7drn'},
      active: function(){
        $.publish('fonts-loaded');
      },
      inactive: function(){
        $.publish('fonts-loaded');
      }
    };
    (function() {
      var wf = document.createElement('script');
      wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
      wf.type = 'text/javascript';
      wf.async = 'true';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(wf, s);
    })();
  </script>
  <!-- start Mixpanel --><script type="text/javascript">(function(c,a){window.mixpanel=a;var b,d,h,e;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src=("https:"===c.location.protocol?"https:":"http:")+'//api.mixpanel.com/site_media/js/api/mixpanel.2.js';d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d);a._i=[];a.init=function(b,c,f){function d(a,b){var c=b.split(".");2==c.length&&(a=a[c[0]],b=c[1]);a[b]=function(){a.push([b].concat(Array.prototype.slice.call(arguments,0)))}}var g=a;"undefined"!==
typeof f?g=a[f]=[]:f="mixpanel";g.people=g.people||[];h="disable track track_pageview track_links track_forms register register_once unregister identify name_tag set_config people.set people.increment".split(" ");for(e=0;e<h.length;e++)d(g,h[e]);a._i.push([b,c,f])};a.__SV=1.1})(document,window.mixpanel||[]);
mixpanel.init("67915f9fee8b35dfc6375ebe93c89698");</script><!-- end Mixpanel -->
</head>
<body>

<%= yield %>

</body>
</html>

app/views/prelaunch_subscribers/_form.html.erb
<%= form_for(@prelaunch_subscriber) do |f| %>
  <% if @prelaunch_subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prelaunch_subscriber.errors.count, "error") %> prohibited this prelaunch_subscriber from being saved:</h2>

      <ul>
      <% @prelaunch_subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :portfolio %><br />
    <%= f.text_field :portfolio %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br />
    <%= f.date_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prelaunch_subscribers/edit.html.erb
<h1>Editing prelaunch_subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @prelaunch_subscriber %> |
<%= link_to 'Back', prelaunch_subscribers_path %>

app/views/prelaunch_subscribers/index.html.erb
<h1>Listing prelaunch_subscribers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Portfolio</th>
    <th>Birthdate</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prelaunch_subscribers.each do |prelaunch_subscriber| %>
  <tr>
    <td><%= prelaunch_subscriber.name %></td>
    <td><%= prelaunch_subscriber.email %></td>
    <td><%= prelaunch_subscriber.phone %></td>
    <td><%= prelaunch_subscriber.portfolio %></td>
    <td><%= prelaunch_subscriber.birthdate %></td>
    <td><%= prelaunch_subscriber.location %></td>
    <td><%= link_to 'Show', prelaunch_subscriber %></td>
    <td><%= link_to 'Edit', edit_prelaunch_subscriber_path(prelaunch_subscriber) %></td>
    <td><%= link_to 'Destroy', prelaunch_subscriber, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prelaunch subscriber', new_prelaunch_subscriber_path %>

app/views/prelaunch_subscribers/new.html.erb
<div class="panel" id="panel">
	<div class="persistent">
		<h1 class="lobster">Impasto</h1>
		<h2 class="rooney">Rethinking the global art marketplace.</h2>
		<p class="chap desc">Impasto is a digital marketplace that brings together artists, buyers, and collectors. It's a place where emerging artists can tell their stories and anyone can buy incredible, original pieces from around the world. Impasto eliminates the barriers galleries impose by creating a world class space where buyers and artists can deal directly with one another.</p>
	</div>

	<div class="intro clearfix" id="intro-box">
		<!-- <h3 class="rooney">I'm</h3> -->
		<div class="buttons">
			<a id="artist-button" class="btn btn-inverse lobster">I'm an Artist</a>
			<a id="user-button" class="btn btn-inverse lobster">I'm a Collector</a>
		</div>
	</div>

	<div class="share" id="share-box">
		<h3 class="rooney">Thanks! <br> We'll let you know as soon we're open.</h3>
	</div>

	<div class="artist" id="artist-box">
		<h3 class="rooney">Enter your Information</h3>
		<%= form_for @prelaunch_subscriber, :url => { :action => "create" } do |f| %>
			<%= label(:prelaunch_subscriber, :email, "Email (required)") %>
			<%= f.text_field :email, :class => "span4", :placeholder => "ex. name@exmaple.com" %>
			<br>
			<%= f.label :name, :class => "chap" %>
			<%= f.text_field :name, :class => "span4", :placeholder => "ex. John Smith" %>

			<br>
			<%= f.label :phone, :class => "chap" %>
			<%= f.text_field :phone, :class => "span4", :placeholder => "ex. (212)-555-1212" %>

			<br>
			<%= f.label :portfolio, :class => "chap" %>
			<%= f.text_field :portfolio, :class => "span4", :placeholder => "ex. http://www.example.com/" %>

			<br>
			<%= f.label :location, :class => "chap" %>
			<%= f.text_field :location, :class => "span4", :placeholder => "ex. New York, NY" %>

			<br>
			<%= f.label :birthdate %>

			<div class="dates">
				<%= f.date_select :birthdate, :order => [:month, :day, :year], :start_year => 1900, :end_year => 2012 %>
			</div>

			<%= f.hidden_field :artist, :value => 1 %>
			<button class="btn btn-success lobster" type="submit">Sign Up</button>
		<% end %>
	</div>

	<div class="user" id="user-box">
		<h3 class="rooney">Enter Email (Required)</h3>
		<%= form_for @prelaunch_subscriber, :url => { :action => "create" } do |f| %>
			<div class="input-append">
				<%= f.text_field :email, :class => "span4", :placeholder => "ex. name@exmaple.com" %>
				<button type="submit" class="btn btn-success">Go</button>
			</div>

			<%= f.hidden_field :artist, :value => 0 %>
		<% end %>
	</div>
</div>

app/views/prelaunch_subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @prelaunch_subscriber.name %>
</p>

<p>
  <b>Email:</b>
  <%= @prelaunch_subscriber.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @prelaunch_subscriber.phone %>
</p>

<p>
  <b>Portfolio:</b>
  <%= @prelaunch_subscriber.portfolio %>
</p>

<p>
  <b>Birthdate:</b>
  <%= @prelaunch_subscriber.birthdate %>
</p>

<p>
  <b>Location:</b>
  <%= @prelaunch_subscriber.location %>
</p>


<%= link_to 'Edit', edit_prelaunch_subscriber_path(@prelaunch_subscriber) %> |
<%= link_to 'Back', prelaunch_subscribers_path %>